server:
  port: 8091

spring:
  cloud:
    config:
      server:
        git:
          uri:  http://192.168.20.183/root/configure.git
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"