server:
  port: 8091

spring:
  cloud:
    config:
      server:
        git:
          uri: git경로를 사용하세요.
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
